const types = {
    //modal
    MODAL_OPEN: 'MODAL_OPEN',
    MODAL_CLOSE: 'MODAL_CLOSE',

    //popover

    OPEN_POPUP: 'OPEN_POPUP',
    CLOSE_POPUP: 'CLOSE_POPUP',

    //auth


    SEND_OTP_LOADING: 'SEND_OTP_LOADING',
    SEND_OTP_SUCCESS: 'SEND_OTP_SUCESS',
    SEND_OTP_FAILED: 'SEND_OTP_SUCESS',

    VERIFY_OTP_LOADING: 'VERIFY_OTP_LOADING',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCESS',
    VERIFY_OTP_FAILED: 'VERIFY_OTP_SUCESS',

    REGISTER_LOADING: 'REGISTER_LOADING',
    REGISTER_SUCCESS: 'REGISTER_SUCESS',
    REGISTER_FAILED: 'REGISTER_SUCESS',
    //all Destinations
    ALL_DESTINATIONS_LOADING: 'ALL_DESTINATIONS_LOADING',
    ALL_DESTINATIONS_SUCCESS: 'ALL_DESTINATIONS_SUCESS',
    ALL_DESTINATIONS_FAILED: 'ALL_DESTINATIONS_SUCESS',

    //all Destinations
    TOP_UNIVERSITIES_LOADING: 'TOP_UNIVERSITIES_LOADING',
    TOP_UNIVERSITIES_SUCCESS: 'TOP_UNIVERSITIES_SUCESS',
    TOP_UNIVERSITIES_FAILED: 'TOP_UNIVERSITIES_SUCESS',

    //all Universities
    ALL_UNIVERSITIES_LOADING: 'ALL_UNIVERSITIES_LOADING',
    ALL_UNIVERSITIES_SUCCESS: 'ALL_UNIVERSITIES_SUCESS',
    ALL_UNIVERSITIES_FAILED: 'ALL_UNIVERSITIES_SUCESS',

    //all Destinations
    SINGLE_UNIVERSITY_LOADING: 'SINGLE_UNIVERSITY_LOADING',
    SINGLE_UNIVERSITY_SUCCESS: 'SINGLE_UNIVERSITY_SUCESS',
    SINGLE_UNIVERSITY_FAILED: 'SINGLE_UNIVERSITY_SUCESS',

    //all Destinations
    SINGLE_COURCE_LOADING: 'SINGLE_COURCE_LOADING',
    SINGLE_COURCE_SUCCESS: 'SINGLE_COURCE_SUCESS',
    SINGLE_COURCE_FAILED: 'SINGLE_COURCE_SUCESS',

    //all Destinations
    COUNCELLORS_LOADING: 'COUNCELLORS_LOADING',
    COUNCELLORS_SUCCESS: 'COUNCELLORS_SUCESS',
    COUNCELLORS_FAILED: 'COUNCELLORS_SUCESS',

    //all Destinations
    USER_PROFILE_LOADING: 'USER_PROFILE_LOADING',
    USER_PROFILE_SUCCESS: 'USER_PROFILE_SUCESS',
    USER_PROFILE_FAILED: 'USER_PROFILE_SUCESS',

    //all Destinations
    EDIT_USER_PROFILE_LOADING: 'EDIT_USER_PROFILE_LOADING',
    EDIT_USER_PROFILE_SUCCESS: 'EDIT_USER_PROFILE_SUCESS',
    EDIT_USER_PROFILE_FAILED: 'EDIT_USER_PROFILE_SUCESS',

    //dashboard
    DASHBOARD_LOADING: 'DASHBOARD_LOADING',
    DASHBOARD_SUCCESS: 'DASHBOARD_SUCESS',
    DASHBOARD_FAILED: 'DASHBOARD_SUCESS',

    SET_CONSTANTS: 'SET_CONSTANTS',

    //layout types

    layout: {

        OTP_FORM_MODAL: 'OTP_FORM_MODAL',
        APPLY_NOW_MODAL: 'APPLY_NOW_MODAL',


        AUTH_FORM_TYPE: 'AUTH_FORM_TYPE',
        REGISTER_FORM: 'REGISTER_FORM',
        SEND_OTP_FORM: 'SEND_OTP_FORM',

        COURSE_PREFERENCE_FORM_MODAL: 'COURSE_PREFERENCE_FORM_MODAL',
        COUNTRY_PREFERENCE_FORM_MODAL: 'COUNTRY_PREFERENCE_FORM_MODAL',
        SKILLS_FORM_MODAL: 'SKILLS_FORM_MODAL',

        EDIT_EXPERIENCES_FORM_MODAL: 'EDIT_EXPERIENCES_FORM_MODAL',
        EDIT_EDUCATIONS_FORM_MODAL: 'EDIT_EDUCATIONS_FORM_MODAL',

        EDIT_SCORES_FORM_MODAL: 'EDIT_SCORES_FORM_MODAL',

        ALL_COURCES_LIST_MODAL: 'ALL_COURCES_LIST_MODAL',

        OPEN_TOP_TOAST: ' OPEN_TOP_TOAST',
        CLOSE_TOP_TOAST: 'CLOSE_TOP_TOAST'


    }
}

export default types